pages:
  image: node:alpine
  stage: build
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    expire_in: 1 day
    paths:
      - public
  only :
      - main

unit test:
  script:
    - npm install
    - npm run test

